# This file was generated by GoReleaser. DO NOT EDIT.
cask "baton" do
  version "2.2.1"

  on_macos do
    on_intel do
      sha256 "da6934765e507180685e9c5f0dae2c51f2d44aeb229c39591c49c6c943c947e8"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79945709e70febaa25303161426683262824fbd367a63b8a85b51d9d40ae3895"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d70e6294f08cd36b1fa237238dcc367c38070771fae3a66602ba29b87ff492b"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0aeb405d1ed6c1f5086c884039eb35714b5ecdb8eee0eb04327f07049bf44bfe"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baton"
  desc "An extensible, agent-friendly terminal multiplexer"
  homepage "https://github.com/cmj0121/baton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baton"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/baton"]
    end
  end

  # No zap stanza required

end
