# This file was generated by GoReleaser. DO NOT EDIT.
cask "baton" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "889f88bc26366a81d890034caa07b84eebb0bca743941acf1522b63b5658b88e"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "606f77aaa149eab25c5e200098d412e53dc89dc46042071f6ae002ed91741c0e"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e10fc010110d0d550309538475b11cf573863be152dc9b9739b42e6612ea963"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dd67c1c95e2def4fef4e880f2815e089c5c1a63af403c12648b9986df88d691"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baton"
  desc "An extensible, agent-friendly terminal multiplexer"
  homepage "https://github.com/cmj0121/baton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baton"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/baton"]
    end
  end

  # No zap stanza required

end
