# This file was generated by GoReleaser. DO NOT EDIT.
cask "baton" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "981576a2f484941c4c96e40a22809863b4400847044fad9c8085518d1c154741"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd3d7a5fcba8cbfac646bd73858a925bacc673240fd97d9873f92f571cdffee7"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34f6abb30f5848938505e30813a89acbaf4f94a46a7263faf07e0fa3009cfd5b"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9066f2264be733494eff84b6a1f9c651ea36e789fdf29bce090134409a67a89"
      url "https://github.com/cmj0121/baton/releases/download/v#{version}/baton_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baton"
  desc "An extensible, agent-friendly terminal multiplexer"
  homepage "https://github.com/cmj0121/baton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baton"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/baton"]
    end
  end

  # No zap stanza required

end
